### ISSUE TITLE
Use for adding pages visible only to registered members?

### ISSUE THREAD

**Issue by blakenzoe** [bolt/Members#15]
Is this extension able to provide me with the tools necessary to sign up and log in users that, depending on their assigned roles, could access members-only sections of my website? Is this a Bolt 2.x extension or do I need to wait for Bolt 3.0?

**Comment by GawainLynch** [comment]
> Is this extension able to provide me with the tools necessary to sign up and log in users that, depending on their assigned roles, could access members-only sections of my website? 

Absolutely, yes. It needs the documentation written up still but we're already using it.

> Is this a Bolt 2.x extension or do I need to wait for Bolt 3.0?

Bolt 3. The extension was originally written for Bolt 2, but the rewrite uses features from Bolt 3... Lots of them. Also the libraries require Guzzle 6 and PHP 5.5.9+ so that was yet another factor.

**Comment by blakenzoe** [comment]
Sorry, two more questions: Does it come with a UI for managing members? When/how do I get Bolt 3?

**Comment by GawainLynch** [comment]
> Sorry, two more questions: 

Questions are always welcome :smile: 

> Does it come with a UI for managing members? 

Yes, there is a sub-menu of "Extend" in the admin section:
![image](https://cloud.githubusercontent.com/assets/1427081/13804469/8a3e38c0-eb4d-11e5-9b46-0ad5c0def442.png)

> When/how do I get Bolt 3?

We hope to release Beta 1 next Wednesday, and there will be accompanying zip/tar files available. 

If you use git or Composer installs, you can update that way… But there is lots of missing documentation so be warned :grin:

**Comment by kehugter** [comment]
> Questions are always welcome

Great! Another one: is there's an ETA for this extension to hit extensions.bolt.cm?

**Comment by GawainLynch** [comment]
[It already is](http://extensions.bolt.cm/view/aa8ae707-3e53-11e4-bc30-279fa66403e0)… But note that the current working `dev-master` is only for the upcoming Bolt 3 (beta 1 released a couple of days ago)

**Comment by kehugter** [comment]
> for the upcoming Bolt 3

Yes, that was actually the question, I didn't phrase it well. What I meant to say was: when will this extension be available for Bolt 3 at extensions.bolt.cm?

**Comment by GawainLynch** [comment]
So it is available now if you set your extensions config to allow `dev` installs.

A tagged version… some time after Bolt 3 is released.
