### ISSUE TITLE
cannot add that extension through bolt backend

### ISSUE THREAD

**Issue by dadaxr** [bolt/Members#17]
when i want to add that extention it to my current installation ( bolt 3 beta 2 ) :

```
Loading composer repositories with package information
Updating dependencies
Your requirements could not be resolved to an installable set of packages.

 Problem 1
   - Installation request for bolt/members dev-master -> satisfiable by bolt/members[dev-master].
   - bolt/members dev-master requires ramsey/uuid ^3.1 -> no matching package found.

Potential causes:
- A typo in the package name
- The package is not available in a stable-enough version according to your minimum-stability setting
  see this link for more details.

Read this link for further common problems.

```

but there is a valid branch tagged with 3.1.0 for that ramsey/uuid on packagist... but as @SahAssar  told me : the composer config used for bolt extensions does not look into packagist repo, but only in http://extensions.bolt.cm/satis/

according to @sahassar : 

> The usual practice up until now has been to bundle dependencies like the GA extension does, but that's not optimal, so I think that gawain and the rest hope to have a small set of common, crucial packages from packagist in the extension satis. (I think, if someone online knows more please correct me.)

Is there any solution to install that extension in my bolt 3 beta 2 installation ?

**Comment by GawainLynch** [comment]
Something has broken badly with my PR that @rossriley merged today… having a look now.

**Comment by GawainLynch** [comment]
OK… super dumb path problem on that PR… fixed and the update should take effect in 30 minutes.

**Comment by dadaxr** [comment]
it's Working :)
Thanks a lot !
