### ISSUE TITLE
Debug: false in my config file

### ISSUE THREAD

**Issue by slummer87** [bolt/Members#19]
When I did change my debug value to false in config.yml this error occur: 
`Catchable fatal error: Argument 4 passed to Bolt\Extension\Bolt\Members\EventListener\ProfileListener::__construct() must be an instance of Symfony\Component\EventDispatcher\Debug\TraceableEventDispatcherInterface, instance of Symfony\Component\EventDispatcher\EventDispatcher given, called in /var/www/project/extensions/vendor/bolt/members/src/Provider/MembersServiceProvider.php on line 461 and defined in /var/www/project/extensions/vendor/bolt/members/src/EventListener/ProfileListener.php on line 47`

**Comment by GawainLynch** [comment]
Thanks!

Fixed in efb09aa88a779aff41fe7dd14d90835a070a1663
