### ISSUE TITLE
Disable account not working

### ISSUE THREAD

**Issue by slummer87** [bolt/Members#20]
When I disable account in members extension I'm still able to log in to this account. I think there is a bug. Can you check it?

**Comment by GawainLynch** [comment]
Not complete functionality yet.

**Comment by GawainLynch** [comment]
Fixed in 7ac83732764d411bfc4b7f8cf96822b59699ac40 and 20a433b5ad8d21f85a4157460fbb32267f7d720d

**Comment by slummer87** [comment]
Thanks!
