### ISSUE TITLE
Error during mysql update

### ISSUE THREAD

**Issue by rkarkut** [bolt/Members#21]
When I'm trying to update my database error occur: 

> An error occured while updating `bolt_members_account`. The error is An exception occurred while executing 'ALTER TABLE bolt_members_account CHANGE roles roles LONGTEXT DEFAULT 'Array' NOT NULL COMMENT '(DC2Type:json_array)'': SQLSTATE[42000]: Syntax error or access violation: 1101 BLOB, TEXT, GEOMETRY or JSON column 'roles' can't have a default value
> 
>  An error occured while updating `bolt_members_provider`. The error is An exception occurred while executing 'ALTER TABLE bolt_members_provider CHANGE refresh_token refresh_token LONGTEXT DEFAULT 'Array' NOT NULL COMMENT '(DC2Type:json_array)', CHANGE resource_owner resource_owner LONGTEXT DEFAULT 'Array' NOT NULL COMMENT '(DC2Type:json_array)'': SQLSTATE[42000]: Syntax error or access violation: 1101 BLOB, TEXT, GEOMETRY or JSON column 'refresh_token' can't have a default value
> 
> An error occured while updating `bolt_members_token`. The error is An exception occurred while executing 'ALTER TABLE bolt_members_token CHANGE token_data token_data LONGTEXT DEFAULT 'Array' NOT NULL COMMENT '(DC2Type:json_array)'': SQLSTATE[42000]: Syntax error or access violation: 1101 BLOB, TEXT, GEOMETRY or JSON column 'token_data' can't have a default value

I'm using mysql Ver 14.14 Distrib 5.7.12

Any advice how to fix this problem?

**Comment by SahAssar** [comment]
Closing, since it's almost a year old, if it's still an issue with the latest dev-master or the next release, please reopen,  but I haven't run into this during the last half year or so of using members.
