### ISSUE TITLE
confirmation email

### ISSUE THREAD

**Issue by rkarkut** [bolt/Members#22]
Why confirmation email is send if my account is already enabled and I'm already logged in (before I confirmed my account using link from email). IMHO it doesn't make sense to send this email. What do you think?

**Comment by GawainLynch** [comment]
I think configurable in the future is OK… but I can enter me@here.com as an email address, but I can guarantee that isn't my email address :wink:

**Comment by slummer87** [comment]
Yes, but IMO account should not be enabled by default and should not be possible to login if account is not verified. What do you think? :)

**Comment by GawainLynch** [comment]
> Yes, but IMO account should not be enabled by default 

I disagree. Unless I am missing something in your point, that would render the extension useless for sites that just want "membership" functionality.

> and should not be possible to login if account is not verified.

That only fits a single use case, that is up to individual implementation. 

For example the project we are currently working on, that is exactly what the do **not** want.

**Comment by slummer87** [comment]
OK, thanks for your answer. What exactly happen when I click on confirmation email? I don't see any changes right now ;)

**Comment by GawainLynch** [comment]
Nothing yet… there is still a bit to do on things before we tag a release… So much work, not enough hours in the day :laughing: 

Oh, with the discussion above… one of the things I was trying to highlight (in case it wasn't clear) is that we think that Members as an extension should be fairly general in its approach. So specific use cases should be able to be handled by add-on extensions [like this one](https://github.com/bolt/Members-Addon-Example).

**Comment by slummer87** [comment]
OK great, I like the idea to extend your extension. I will check it :) Thanks for your replies.

**Comment by GawainLynch** [comment]
No problem… I have added a lot of Symfony events at different places too (and am open to adding more) to help people who extend.

**Comment by dantleech** [comment]
Just to chime in - I also think this is counter-intutive default behavior - this would enable bots to login to the site and have membership privleges (e.g. posting comments etc.).

**Comment by SahAssar** [comment]
Closing as this seems to be outdated, Please reopen or open a new issue if this is still an issue in the next version (to be tagged soon), but this seems like it'd require a proper spec of what the new use-case should be and how it should behave (Preferably in the form of a RFC and a PR).
