### ISSUE TITLE
cannot use form type data_class attribute

### ISSUE THREAD

**Issue by dadaxr** [bolt/Members#23]
With the actual implementation it's not possible (i think) to use the data_class form type attribute.
If i try i get : 

> the form's view data is expected to be an instance of class Bolt\Extension\Bolt\Members\Form\Entity\Profile  but is a(n) array

The problem : in the different Form Managers ( ProfileEdit / ProfileRegister / etc ), wihtin the getData() method, you return an array with a "data" key which is an array. This data array prevent us to use the data_class attribute ( because of type missmatch between the entity value object and the overided data ).

Instead, i think you should return the entity with the data setted ( through setter ).

ie : 

```
//extensions\vendor\bolt\members\src\Form\ProfileRegister.php
protected function getData(Storage\Records $records)
    {
        if ($this->session === null) {
            throw new \RuntimeException('Members session not set.');
        }

        $fields = [];
        if ($this->session->isTransitional()) {
            $resourceOwner = $this->session->getTransitionalProvider()->getResourceOwner();
            /**$fields = [
                'displayname' => $resourceOwner->getName(),
                'email'       => $resourceOwner->getEmail(),
            ];*/
            $this->entity->setDisplayname($resourceOwner->getName());
            $this->entity->setEmail($resourceOwner->getEmail());
        }

        return [
            'csrf_protection' => true,
            'data'            => $this->entity
        ];
    }
```

What do you think ?

**Comment by GawainLynch** [comment]
Sure, if you have time to PR something, we can talk it over further.
