### ISSUE TITLE
Addition to feedback.twig

### ISSUE THREAD

**Issue by peterboorsma** [bolt/Members#31]
I think it's a good idea to give the ul's in feedback.twig a classname. That way it's much easier for frontenders to style form messages.

from:
```
        <ul>
            {% for message in feedback.error %}
                <li>{{ message }}</li>
            {% endfor %}
        </ul>
```

to:

```
        <ul class="members-feedback-messages">
            {% for message in feedback.error %}
                <li>{{ message }}</li>
            {% endfor %}
        </ul>
```

See attached version of [feedback.twig.zip](https://github.com/bolt/Members/files/336995/feedback.twig.zip) (zipped)

**Comment by GawainLynch** [comment]
Updated the default template.
