### ISSUE TITLE
CSS in Bolt 3.08

### ISSUE THREAD

**Issue by dantleech** [bolt/Members#32]
Public name field is obscured

![screenboltmem](https://cloud.githubusercontent.com/assets/530801/16656901/5d2dbf86-4458-11e6-9618-c34a26fd68bd.png)

**Comment by GawainLynch** [comment]
I don't suppose you have any idea what is going on there, as I can't reproduce here :disappointed:

**Comment by dantleech** [comment]
It works in chrome, this in FF/Iceweasel 38.2.1 - also works in webkitGTK. Will have a closer look.

**Comment by GawainLynch** [comment]
Ah, right… should have "look up" (i.e. address bar)…

I totally suck at anything presentation layer, and literally stay well out of conversations on it as I am very good at some things, visual is not one. I still try to use `<blink></blink>` and can spend an hour or more figuring out why it doesn't work … or isn't 1995, you tell me.

Any and all help most welcome `**cough**` @bobdenotter @SahAssar :stuck_out_tongue_winking_eye:

**Comment by SahAssar** [comment]
I'll take a looksie :)

**Comment by SahAssar** [comment]
@dantleech works fine in FF45 on windows and FF47 on ubuntu (the two OS'es I have in front of me currently)... Is this strictly a FF/Iceweasel <40 issue? If you open the devtools can you see the input element there?

**Comment by SahAssar** [comment]
Oh, shit, sorry, didn't see that the input was floated to the side. I'll load up a FF38 and check it out.

**Comment by SahAssar** [comment]
The issue is that the input elements use columns, but the form is not set as a "row". So, making sure that the container (the form) is a row should fix this.

Tested in browserstack on FF38.

**Comment by dantleech** [comment]
Thanks @GawainLynch and @SahAssar !

**Comment by GawainLynch** [comment]
100% @SahAssar on this one… we team up well!
