### ISSUE TITLE
"Invalid email" when creating user from the backoffice.

### ISSUE THREAD

**Issue by dantleech** [bolt/Members#33]
Valid email is stated to be invalid (quotes?):

![profile](https://cloud.githubusercontent.com/assets/530801/16656977/a0112428-4458-11e6-83f6-a42672fb6e22.png)

Also "Edit New Profile" :)

**Comment by GawainLynch** [comment]
This is 100% correct. The validator does an MX look up on the domain, and `example.com` is a [legitimately reserved TLD per RFC 2606](https://tools.ietf.org/html/rfc2606) that MUST be recognised as invalid.
