### ISSUE TITLE
[RFC] Connection between Bolt and Members users

### ISSUE THREAD

**Issue by PhillippOhlandt** [bolt/Members#35]
I already talked with @GawainLynch about this, so this issue is more like a reminder.

The first connection between the Members and Bolt users should be a shared login. Means that when I log in via Members, I am also logged in via my Bolt user (when I have one).
This could also work in both directions but personally, I would be completely fine with Members => Bolt.

And there is another thing, that just came into my mind: 
It would be nice to access the linking between two accounts. Let's say I have the Bolt user account, then I could get the linked Members account via a getter or something. The same in the other direction. Both available via PHP and twig functions.

The linking between a Bolt and Members account could be established by the same email address.

**Comment by GawainLynch** [comment]
OK, I am in two minds about this.

On the one hand, it would allow federated login… opening the door to SSO for multiple Bolt installs under an entities control.

Also worth noting is that Members now allows password based login, so the dependence on 3rd parties is removed in that instance.

**Comment by bobdenotter** [comment]
Hmm, I'm going to think this over.. It's not something i want to shoot down out of the blue, but it should be considered carefully. (mainly to minimize the risk of users 'leaking' sensitive data, if the connection isn't done carefully enough)

**Comment by PhillippOhlandt** [comment]
@bobdenotter yes, that's just an idea for the future and not for RIGHT NOW :) And of course, it has to be done carefully but Gawain has all my trust in this :)

**Comment by SahAssar** [comment]
For companies like intendit this would be very, very useful, so :+1: from me (if we can find a secure, sane way to do it)!

**Comment by GawainLynch** [comment]
For the sake of keeping this one on track, I have added it as an agenda item for [next Tuesday](https://github.com/bolt/bolt/wiki/Dev-meeting-2016-07-12)

**Comment by PhillippOhlandt** [comment]
You mean ... discussing it with Ross? Bye feature xD

**Comment by SahAssar** [comment]
I'd love this (As I said above), but the focus for this is frontend for now. Closing until someone gets around to getting it done, since it isn't doing any good open :)
