### ISSUE TITLE
Could not find package bolt/members

### ISSUE THREAD

**Issue by isularifin** [bolt/Members#37]
hi,
I have tried to install bolt member on bolt 3.0.11. But i have got error like this...

Could not find package bolt/members at any version for your minimum-stability (stable). Check the package spelling or your minimum-stability
File: /vendor/bolt/bolt/src/Composer/Action/BaseAction.php::198

Thanks.

**Comment by GawainLynch** [comment]
There is no stable version of Members yet, you will need to lower the stability level in [config.yml](https://github.com/bolt/bolt/blob/release/3.0/app/config/config.yml.dist#L392)
