### ISSUE TITLE
Password form not appearing & Facebook throwing an error.

### ISSUE THREAD

**Issue by jmcmullen** [bolt/Members#4]
I'm unable to get the password form to appear however the Facebook option appears, and shows an error once the user has approved access to his account. 

This is happening at: http://whiterabbit.qnodes.com/fresh-start

The Facebook error is: 
```Catchable fatal error: Argument 2 passed to Bolt\Extension\Bolt\ClientLogin\ClientRecords::doCreateUserProfile() must be of the type array, object given, called in /home/whiterabbit/public_html/extensions/vendor/bolt/clientlogin/src/Session.php on line 86 and defined in /home/whiterabbit/public_html/extensions/vendor/bolt/clientlogin/src/ClientRecords.php on line 224```

**Comment by GawainLynch** [comment]
Closing as the extension has merge with `bolt/clientlogin` and has been rewritten in the process.
