### ISSUE TITLE
PostgreSQL support

### ISSUE THREAD

**Issue by artggd** [bolt/Members#59]
I'm using PostgreSQL on my website. Members crashes on the list page in the admin.

<img width="1002" alt="capture d ecran 2016-11-30 a 10 50 10" src="https://cloud.githubusercontent.com/assets/1837559/20747566/d1eb43b6-b6ea-11e6-8ed1-3c0bb3d92958.png">

This is due to the pager doing a count() to get the total results. This count utilises the same query as the one fetching the results. That query has an order by clause, the bug happens here ; MySQL loosely supports counting items ordered by a column but most db systems would require that column to be in a group by clause, PostgreSQL included.

PR on its way

**Comment by GawainLynch** [comment]
> PR on its way

Sweet, I like your style :+1:
