### ISSUE TITLE
[bug] remote font awesome stylesheet in templates

### ISSUE THREAD

**Issue by jadwigo** [bolt/Members#62]
In the bolt back-end font-awesome is loaded from remote:
- https://github.com/bolt/Members/blob/master/templates/admin/profile_edit.twig#L19
- https://github.com/bolt/Members/blob/master/templates/admin/profile_add.twig#L19

As bolt has font-awesome built-in and locally that should not be needed.

The members front-end page has it too
- https://github.com/bolt/Members/blob/master/templates/profile/edit.twig#L15

But in this case it should not be needed either, because the front-end theme should handle these icons.

**Comment by GawainLynch** [comment]
> In the bolt back-end font-awesome is loaded from remote:

There was a valid reason at the time with what icons Bolt had. Have you tested with those removed?

> The members front-end page has it too

That stays, as there is no guarantee and these are default templates aimed to be overridden/replaced.

**Comment by jadwigo** [comment]
I would rather remove all external dependencies if it is supposed to be overridden anyway. You could use unicode emoji's instead, those are future proof-ish

Haven't tested either

**Comment by SahAssar** [comment]
I'm thinking this is one of those that will be PR'ed soon, and since we are cleaning this repo's issues I'm closing. If nobody get's ahead of me I'll PR a fix soon since I always get irritated by external resources :D
