### ISSUE TITLE
Which is the easiest way to remove Public Name field?

### ISSUE THREAD

**Issue by minthemiddle** [bolt/Members#65]
`Public Name` is not needed for my use case, an email address for identification is enough. I tried to just uncomment the form field in the Twig registration form, but that did not work. I could not find any config setting either. It seems to be hardwired into the user model.

Which is the easiest way to get rid of the `Public name` field?

**Comment by GawainLynch** [comment]
It just uses Symfony Forms … you can just set the field on rendered in th eTwig template

**Comment by minthemiddle** [comment]
Just for reference:

In `extensions/vendor/bolt/members/templates/profile/registration/register.twig` uncomment `{# {{ form_row(form_register.displayname, { 'value': member.name|default() } ) }} #}` and add `{% do form_register.displayname.setRendered %}`

**Comment by leggewie** [comment]
Thank you, @minthemiddle for documenting your solution in detail.

**Comment by GawainLynch** [comment]
Just for reference, the templates that ship with the extension are designed to be overridden. They are simply "defaults" to give a base to build on.

See the documentation on template [overrides](https://github.com/bolt/Members/blob/master/doc/form-display.md#template-overrides)
