### ISSUE TITLE
How to redirect after succesful login or logout

### ISSUE THREAD

**Issue by MarienTimOnline** [bolt/Members#66]
I cannot find how to redirect after a succesful login or logout... I'm sure I'm overlooking it...
Has to be some config setting right?!

**Comment by GawainLynch** [comment]
Should be [documented here](https://github.com/bolt/Members/blob/master/doc/redirection.md)

**Comment by MarienTimOnline** [comment]
tried this at least 5 times yesterday... no workie workie...
Tried it once today... works...

I should stop for the week... ;).
Thnx Gawain! Fixed!

**Comment by GawainLynch** [comment]
Haha … Yeah, sounds like my day(s).
