### ISSUE TITLE
Best way to check user in (other) extension

### ISSUE THREAD

**Issue by MarienTimOnline** [bolt/Members#67]
I have a Twig function in a different extension in which I'd like to check if a user is logged in (and which user).
How should I go about this? Is there a simple route to take?

I'd like {{ is_member() }} and {{ member() }} in my other extension, so to speak :).

**Comment by MarienTimOnline** [comment]
{{ is_member() }} and {{ member() }} are twig-functions of course. But I'd like them in PHP. Just to be clear.

**Comment by GawainLynch** [comment]
```php
$memberSession = $app['members.session'];
if ($memberSession->hasAuthorisation()) {
    /** @var \Bolt\Extension\Bolt\Members\AccessControl\Authorisation $authObject */
    $authObject = $memberSession->getAuthorisation();
    /** @var \Bolt\Extension\Bolt\Members\Storage\Entity\Account $memberAccount*/
    $memberAccount =  $authObject->getAccount();
}
```

**Comment by MarienTimOnline** [comment]
Hero! Solved also!
Week saved...

**Comment by GawainLynch** [comment]
:+1: :smile:

**Comment by bobdenotter** [comment]
For future google-archeologists: This is now also documented here: https://github.com/bolt/Members/blob/master/doc/examples/fetching-logged-in-member.md

**Comment by GawainLynch** [comment]
> For future google-archeologists

Mate, you so know how to put big smiles on my face :laughing:
