### ISSUE TITLE
Trying to extend with new fields

### ISSUE THREAD

**Issue by MarienTimOnline** [bolt/Members#68]
Hi,

Trying to extend the members with some additional fields in a new extension called 'Membershelper'.
However, when I use the suggested method https://github.com/bolt/Members/blob/master/doc/extending/adding-meta-fields.md#extending-adding-meta-fields

I keep getting this:

`ClassNotFoundException in MembershelperExtension.php line 80:
Attempted to load class "ProfileEditType" from namespace "Bolt\Extension\Timonline\Membershelper\Form\Type".
Did you forget a "use" statement for "Bolt\Extension\Bolt\Members\Form\Type\ProfileEditType"?`

What does it wantttttt from me? ;)

**Comment by MarienTimOnline** [comment]
Found it!!

The example code and example extension code are different and I had some hybrid created...

https://github.com/bolt/Members-Addon-Example/blob/master/src/Form/Entity/Profile.php
and
https://github.com/bolt/Members/blob/master/doc/extending/adding-meta-fields.md

So fixed... but took a while to figure out

**Comment by GawainLynch** [comment]
Ah, need to update docs … thanks!

**Comment by GawainLynch** [comment]
@MarienTimOnline it might be last night's :beers: … but I can't see what's breaking … could you give me a pointer?

**Comment by MarienTimOnline** [comment]
sorry. This was my problem:

The use's at the top of this file:
https://github.com/bolt/Members-Addon-Example/blob/master/src/Form/Type/ProfileEditType.php
Those are correct.

The use's mentioned here:
https://github.com/bolt/Members/blob/master/doc/extending/adding-meta-fields.md#form-type-class
didn't suffice.

**Comment by SahAssar** [comment]
Closing as we did some docs updates a little while ago and we will tag a proper version of 3.0 soon, if it persists in stable please open a new one or reopen this :)
