### ISSUE TITLE
[Bug] Incorrect redirection after login

### ISSUE THREAD

**Issue by leggewie** [bolt/Members#69]
Something is missing in the [docs](https://github.com/bolt/Members/blob/master/doc/quick-start.md) or default configuration.  Here's what I did:

- install bolt 3.2.5 to http://localhost/bolt (this might be key)
- install the member-dev extension

(At this point I'm being warned about minimum-stability settings but the installation seems to go ahead.  Another bug, I think).

- set minimum-stability to dev
- update the database
- enable registration
- Go to http://localhost/bolt/membership/profile/register and fill out the form, hit "Save & Continue"

I am then being taken to http://localhost/membership/profile/register which unsurprisingly errors out with 404 (notice the missing /bolt/).  I suspected a redirection error in .htaccess first but this is unchanged from the default and I can't spot anything obviously wrong.  My money is now on the members extension having a bug if bolt is not installed in the top directory of the webroot.

PS: FWIW, the same happens with http://localhost/bolt/authentication/login (coming from http://localhost/bolt/membership/) redirecting to the non-existent http://localhost/authentication/login after attempting to log in with an existing member (added from the sidebar menu in the backend).

**Comment by leggewie** [comment]
I reconfigured an Apache Virtualhost to /var/www/bolt instead of /var/www for that particular Virtualhost and test again.  I am being redirected to the registration page but no member is created.

**Comment by GawainLynch** [comment]
> I am being redirected to the registration page but no member is created.

That should be correct. The account is created after the registration phase is complete

**Comment by GawainLynch** [comment]
Because the email address is the primary user facing ID, and there is no guarantee that a provider will return a valid email address, and the database table requires non-NULL and unique addresses.

> That's certainly a usability issue.

Not at all, it is a process issue.

**Comment by leggewie** [comment]
It's a usability issue because outgoing mail might not be correctly configured.  If the Members plugin redirected to a page saying "Thank you for becoming a member, we've sent you an e-mail for verification.  Your account will be activated after the verification was successful.  If you don not receive the verification mail within the next 24 hours please go through your spam folder and contact the site owner for help."  

Furthermore,  the [docs](https://github.com/bolt/Members/blob/master/doc/quick-start.md) I linked to ought to be updated to reflect that outgoing mail needs to be working.  Bolt does not require this as far as I can see, my testing installation works just fine without outgoing mail.  So, I was not expecting this requirement.

I'm willing to prepare a PR, at least for the documentation.  Please reopen and give me some time.  It would be nice if you guys allowed a little bit more time for discussion before closing.

**Comment by GawainLynch** [comment]
Bolt should give a working if your email setting are not configured. We're working on improving this in core, but it **must not** be a requirement of an extension to monitor this, that would be a "fail" :smile: 

In core, if you don't have working email settings, things like password resets just won't work.

> I'm willing to prepare a PR, at least for the documentation. Please reopen and give me some time. 

You have a deal :+1: 

> It would be nice if you guys allowed a little bit more time for discussion before closing.

We get inundated endlessly with various forms of "issues" and a lot of them are just questions and discussion, so we tend to close those down quickly (this is about to be re-opened though), as we already have Slack, IRC and a discussion forum for that type of stuff. 

But IMHO, what you reported isn't a bug, hence the close. I already put about 60+ hours per week of **unpaid/free** time into the Bolt ecosystem, so unless someone want to work themselves on corner case features, I just don't have the physical time in my life to meet everyone's needs.

**Comment by leggewie** [comment]
Furthermore, I can add members without having to go through e-mail verification. As admin.  So, this IS confusing (see for example, the comment by @dantleech in bug 22).  And if I understand bug 22 correctly, the process is indeed as I described earlier "In most cases that I'm aware of, the account is created and needs to be verified to become fully active."  In my case, a member is not created at all.

The members plugin is awesome.  It still has a couple of rough edges.  Let your users help you find them and polish them up instead of closing their tickets outright, please.  I am a new user so I might do things that you consider stupid and that make the members plugin fail for me.  Somebody else might fail into the same trap.  Let's try to avoid that to make the experience awesome, OK?

**Comment by leggewie** [comment]
Our comments coincided, thanks for reopening.

**Comment by GawainLynch** [comment]
> Let's try to avoid that to make the experience awesome, OK?

Mate, if you're willing to help out … I am all ears, and ready to help where I can. :+1: 

Best place to get me generally is the #development channel on our [Slack](https://slack.bolt.cm/) (not that I am offline most of today though).

**Comment by leggewie** [comment]
I'm not really a slack guy.  I'm sure we'll find a way to collaborate.

OK, let's see what we are left with in this ticket that's really several issues rolled into one.
- "subdirectory installations are unsupported" carved out to bolt/bolt#6320
- "minimum stability settings have no effect" carved out to bolt/bolt#6302
- I updated the docs in cbdee6e to mention the need to configure outgoing mail, although ultimately docs are only second-best solution.  PR is pending.
  - bolt/configuration-notices#4

Left to be done:
- make the members plugin redirect to a page that says "Thank you for becoming a member, we've sent you an e-mail for verification. Your account will be activated after the verification was successful. If you do not receive the verification mail within the next 24 hours please go through your spam folder and contact the site owner for help." to set the correct expectations on the users' and newbie-admins' end.
- IMHO, the Members should have a warning of its own in the dashboard to inform the admin that unconfigured outgoing mail is not just a potential problem but will completely cripple this particular extension for sure.  I for one was happy to live with being unable to receive password reset mail and thought I would not need outgoing mail.
- verify that once I fix the known issues no others are coming out of hiding

**Comment by GawainLynch** [comment]
> I'm not really a slack guy. I'm sure we'll find a way to collaborate.

IRC is always good, most people seem to prefer Slack so that just was a default suggestion.

I have just tagged beta7 that changes the way emails are produced and split them out into two templates, `html.twg` and `text.twig` … setting `format: text` will *only* send text emails

```
notification:
    name: Site Admin
    email: no-reply@email.com
    format: text
```

**Comment by leggewie** [comment]
I suppose your last comment was directed at bolt/bolt#6301?

**Comment by leggewie** [comment]
I'm happy to report that after moving my installation to the webroot of a vhost, adjusting the canonical name in app/cache/config-cache.json accordingly and clearing the cache I was now able to register my first member.

One thing that I noticed apart from the things that have already been mentioned here and elsewhere is the lack of a logout button on the page I'm being redirected to.  I think that should be there by default.

**Comment by GawainLynch** [comment]
> I suppose your last comment was directed at bolt/bolt#6301?

Well you have issues open everywhere for cross-over topics, so I had to pick somewhere.

> One thing that I noticed apart from the things that have already been mentioned here and elsewhere is the lack of a logout button on the page I'm being redirected to. I think that should be there by default.

You build your won templates, you display what you need. The Twig functions included with the extensions can handle the rendering of certain parts with the needed information attached (like login/out buttons), but that is 100% implementation.

> I'm happy to report that after moving my installation to the webroot of a vhost, adjusting the canonical name in app/cache/config-cache.json accordingly and clearing the cache I was now able to register a member for the first time via membership/profile/register.

Excellent :+1:

**Comment by leggewie** [comment]
Geesh, this constant closing of unfixed issues is getting to be tiring.  Did you miss me documenting "Left to be done" items?  When I carve things out to follow "one issue, one ticket" you complain about "Well you have issues open everywhere for cross-over topics".

Let's just keep this ticket closed indeed and I will open new tickets for the stuff I had documented above.  Seems like unnecessary work for small issues.
