### ISSUE TITLE
[Bug] the plugin expects to be installed in the webroot

### ISSUE THREAD

**Issue by leggewie** [bolt/Members#71]
I thought I had already reported this (explicitly), but it looks like I didn't.

I installed a test installation of bolt in http://localhost/bolt and added the Members extension.  When I go to http://localhost/bolt/membership I am being asked to log in.  After doing so, I am redirected to http://localhost/authentication/login which obviously fails with a 404.  The redirect should have gone to http://localhost/bolt/authentication/login in case the login credentials were wrong.

Apparently, the extension assumes for bolt to be installed directly in the webroot, not in a subdirectory.

**Comment by leggewie** [comment]
Could this be resolved as easily as changing "login:  /membership/profile" to "login:  membership/profile" in the "configuration".  After reading [redirection.md](https://github.com/bolt/Members/blob/master/doc/redirection.md) I'm not even sure which file this configuration is in.  The main app/config/config.yml?

**Comment by GawainLynch** [comment]
> Could this be resolved as easily as changing "login: /membership/profile" to "login

No, it is just used at the mount point passed to Silex's resolver, the initial `/` for the most part means nothing.

As I have mentioned in a few places now, this is nothing at all to do with the extension, sub-directory installs are not officially supported, and have known issues in Bolt at present.

**Comment by leggewie** [comment]
I'm sorry, but I wasn't aware that subdirectory installs are currently explicitly unsupported.  As far as I'm aware that's not really mentioned anywhere.  I guess it's another case for bolt/configuration-notices.

Is it safe to take the current installation, configure a vhost in apache and then continue with that without a subdirectory or do I need to reinstall from scratch?  IOW, is there any cruft in my installation now?

You said bolt has known issues with subdirectory installs.  I for one [can't find](https://github.com/bolt/bolt/issues?utf8=%E2%9C%93&q=is%3Aissue%20is%3Aopen%20subdirectory) anything, though.  To avoid frustrations for new users this should not only be known (by those in the know) but also documented: bolt/bolt#6320.

**Comment by GawainLynch** [comment]
Can you try beta 7, I think I might have worked around the problem.
