### ISSUE TITLE
[BUG] Email-spooler dependency

### ISSUE THREAD

**Issue by artggd** [bolt/Members#84]
Hi,
_Members_ is dependent on bolt/email-spooler since a few months (`"bolt/email-spooler": "^3.0"`), this raises 2 issues preventing any email to be sent.
* The readme has not been updated so there's no way for a newcomer to know they're required to run a command to get their emails sent.
* The dependency is based on a non-functioning (though stable) version of email-spooler. There has been [a fix on the command](https://github.com/bolt/bolt-extension-email-spooler/commit/f5631da7b092a23e3900cf415ac348a643a15527) but no tag yet.

Either removing that dependency or releasing a new stable version of email-spooler would fix it all.

I would personally be in favour of removing that dependency, I reckon spooling every email should be the dev's choice. Also, IMO running a command and/or setting up a cronjob adds a bit of complexity, making _Members_ less quick-to-install / dev-friendly.

I can open another issue on email-spooler's repository if you wish (but I know you guys are related 😉).

Cheers

Details
-------

 - Relevant Bolt Members Version: 3.0.x
 - Relevant Bolt Version: 3.x
 - PHP version: 7.0

**Comment by GawainLynch** [comment]
> I would personally be in favour of removing that dependency

Not at all. There is a very good reason they are spooled… PRs welcome to improve the pooler.

**Comment by artggd** [comment]
Right. I'd be interested to know the reason why they are spooled.

I can't PR because the only need is to release a stable version of email-spooler. I will open another issue on the concerned repository.

**Comment by GawainLynch** [comment]
They are spooled because otherwise they can and do get lost.

An unbelievable amount of people do not set up their SMTP settings, even fewer set them p correctly … then there are the people that use 3rd party services that have the reliability of a Hyundai … Sorry, but losing registration, password resets, and other critical data without fallback is just not sensible and if you think that is the case, give up web development … you're not up to the task.

**Comment by artggd** [comment]
I'll take that explanation. I don't get the raging reply though... 

Still, I don't think you understood my problem as you closed and deleted my issue on email-spooler right away. Would you please try and send a spooled email with the __v3.0.3__ of email-spooler and see by yourself...
